## 하이브 와 연결 후 테이블 조회 및 간단한 `DataFrame` 조작

In [1]:
import pandas as pd
from pyhive import hive
import re

In [46]:
# 하이브 연결
cursor = hive.connect('localhost').cursor()

In [47]:
cursor

In [48]:
# 제약바이오주 의 2019년 1월 4일 주가 조회

sql = """
SELECT s.stk_cd ,s.stk_nm ,s.sec_nm ,s.ex_cd
		,hd.dt ,hd.o_prc ,hd.l_prc ,hd.h_prc ,hd.c_prc ,hd.vol 
		,fy.fin_itm_val 
FROM stock s 
inner join history_dt hd on (s.stk_cd=hd.stk_cd)
inner join finance_y fy on (s.stk_cd=fy.stk_cd)
WHERE s.sec_nm ='제약바이오'
AND s.ex_cd ='KP'
AND hd.dt ='2019-01-04'
AND fy.fin_itm_nm ='주당순이익'
AND fy.yy ='2018'
"""

In [49]:
cursor.execute(sql,encoding='utf8')

In [50]:
# 쿼리를 실행하고 결과를 result에 할당
result = cursor.fetchall()

In [52]:
# result

In [53]:
cursor.description

[('s.stk_cd', 'STRING_TYPE', None, None, None, None, True),
 ('s.stk_nm', 'STRING_TYPE', None, None, None, None, True),
 ('s.sec_nm', 'STRING_TYPE', None, None, None, None, True),
 ('s.ex_cd', 'STRING_TYPE', None, None, None, None, True),
 ('hd.dt', 'DATE_TYPE', None, None, None, None, True),
 ('hd.o_prc', 'DECIMAL_TYPE', None, None, None, None, True),
 ('hd.l_prc', 'DECIMAL_TYPE', None, None, None, None, True),
 ('hd.h_prc', 'DECIMAL_TYPE', None, None, None, None, True),
 ('hd.c_prc', 'DECIMAL_TYPE', None, None, None, None, True),
 ('hd.vol', 'DECIMAL_TYPE', None, None, None, None, True),
 ('fy.fin_itm_val', 'DECIMAL_TYPE', None, None, None, None, True)]

In [18]:
desc = cursor.description
# desc

In [19]:
# 리스트의 행 열 방향을 반대로 바꿈
list(zip(*desc))

[('s.stk_cd',
  's.stk_nm',
  's.sec_nm',
  's.ex_cd',
  'hd.dt',
  'hd.o_prc',
  'hd.l_prc',
  'hd.h_prc',
  'hd.c_prc',
  'hd.vol',
  'fy.fin_itm_val'),
 ('STRING_TYPE',
  'STRING_TYPE',
  'STRING_TYPE',
  'STRING_TYPE',
  'DATE_TYPE',
  'DECIMAL_TYPE',
  'DECIMAL_TYPE',
  'DECIMAL_TYPE',
  'DECIMAL_TYPE',
  'DECIMAL_TYPE',
  'DECIMAL_TYPE'),
 (None, None, None, None, None, None, None, None, None, None, None),
 (None, None, None, None, None, None, None, None, None, None, None),
 (None, None, None, None, None, None, None, None, None, None, None),
 (None, None, None, None, None, None, None, None, None, None, None),
 (True, True, True, True, True, True, True, True, True, True, True)]

In [20]:
# 리스트의 0번째 열, column 리턴 => 컬럼명들
list(zip(*desc))[0]

('s.stk_cd',
 's.stk_nm',
 's.sec_nm',
 's.ex_cd',
 'hd.dt',
 'hd.o_prc',
 'hd.l_prc',
 'hd.h_prc',
 'hd.c_prc',
 'hd.vol',
 'fy.fin_itm_val')

In [21]:
col_name = list(zip(*desc))[0]

In [44]:
# 리스트컴프리헨션을 통해 각 컬럼명 대문자로 변환
col_name =[x.upper() for x in col_name]
col_name

['S.STK_CD',
 'S.STK_NM',
 'S.SEC_NM',
 'S.EX_CD',
 'HD.DT',
 'HD.O_PRC',
 'HD.L_PRC',
 'HD.H_PRC',
 'HD.C_PRC',
 'HD.VOL',
 'FY.FIN_ITM_VAL']

In [54]:
# re.sub() : 특정 문자를 찾아서 삭제
# \S :문자열
# \. : .
# . 앞의 문자열을 찾아서 삭제

col_name = [re.sub('\S*\.', "", x) for x in col_name]
col_name

['STK_CD',
 'STK_NM',
 'SEC_NM',
 'EX_CD',
 'DT',
 'O_PRC',
 'L_PRC',
 'H_PRC',
 'C_PRC',
 'VOL',
 'FIN_ITM_VAL']

In [55]:
df = pd.DataFrame(result)
df.columns = col_name
df

,STK_CD,STK_NM,SEC_NM,EX_CD,DT,O_PRC,L_PRC,H_PRC,C_PRC,VOL,FIN_ITM_VAL
0,000020,동화약품,제약바이오,KP,2019-01-04,9100.000,9100.000,9700.000,9530.000,115336.000,365.000
1,000220,유유제약,제약바이오,KP,2019-01-04,10050.000,9970.000,10300.000,10200.000,82844.000,639.000
2,000230,일동홀딩스,제약바이오,KP,2019-01-04,12116.000,11830.000,12259.000,12211.000,5895.000,-363.000
3,000520,삼일제약,제약바이오,KP,2019-01-04,19900.000,19650.000,20550.000,20550.000,38394.000,-1621.000
4,001630,종근당홀딩스,제약바이오,KP,2019-01-04,58600.000,57800.000,59800.000,58400.000,3773.000,5481.000
5,002390,한독,제약바이오,KP,2019-01-04,28150.000,27400.000,28950.000,28000.000,151657.000,590.000
6,002720,국제약품,제약바이오,KP,2019-01-04,4070.000,4070.000,4395.000,4275.000,50009.000,128.000
7,003000,부광약품,제약바이오,KP,2019-01-04,20670.000,20583.000,21588.000,21413.000,391200.000,3019.000
8,003060,에이프로젠제약,제약바이오,KP,2019-01-04,1863.000,1765.000,1883.000,1844.000,477730.000,-12.000
9,003220,대원제약,제약바이오,KP,2019-01-04,13865.000,13685.000,14000.000,13955.000,29095.000,1263.000
10,003850,보령제약,제약바이오,KP,2019-01-04,8994.000,8903.000,9132.000,9068.000,128338.000,483.000
11,004720,우리들제약,제약바이오,KP,2019-01-04,7750.000,7650.000,9320.000,8770.000,7419524.000,390.000
12,005250,녹십자홀딩스,제약바이오,KP,2019-01-04,24000.000,24000.000,24750.000,24600.000,64634.000,406.000
13,006280,녹십자,제약바이오,KP,2019-01-04,129500.000,129000.000,134500.000,133000.000,38323.000,3017.000
14,007570,일양약품,제약바이오,KP,2019-01-04,26000.000,25850.000,27850.000,27800.000,70990.000,-269.000
15,009290,광동제약,제약바이오,KP,2019-01-04,6610.000,6400.000,6690.000,6690.000,149423.000,551.000
16,009420,한올바이오파마,제약바이오,KP,2019-01-04,31900.000,31700.000,34550.000,34200.000,789924.000,64.000
17,019170,신풍제약,제약바이오,KP,2019-01-04,6110.000,6110.000,6850.000,6840.000,1526914.000,56.000
18,068270,셀트리온,제약바이오,KP,2019-01-04,197428.000,195083.000,207276.000,206338.000,1207224.000,2100.000
19,102460,이연제약,제약바이오,KP,2019-01-04,13976.000,13486.000,14222.000,14222.000,20559.000,81.000
20,128940,한미약품,제약바이오,KP,2019-01-04,422320.000,417981.000,436783.000,435336.000,38436.000,2201.000
21,170900,동아에스티,제약바이오,KP,2019-01-04,102000.000,102000.000,107500.000,106000.000,27461.000,949.000
22,185750,종근당,제약바이오,KP,2019-01-04,89537.000,89082.000,91809.000,90718.000,24980.000,4313.000
23,234080,JW생명과학,제약바이오,KP,2019-01-04,20750.000,20000.000,20950.000,20900.000,82687.000,999.000
24,249420,일동제약,제약바이오,KP,2019-01-04,19450.000,19350.000,19950.000,19800.000,51197.000,589.000

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   STK_CD       25 non-null     object
 1   STK_NM       25 non-null     object
 2   SEC_NM       25 non-null     object
 3   EX_CD        25 non-null     object
 4   DT           25 non-null     object
 5   O_PRC        25 non-null     object
 6   L_PRC        25 non-null     object
 7   H_PRC        25 non-null     object
 8   C_PRC        25 non-null     object
 9   VOL          25 non-null     object
 10  FIN_ITM_VAL  25 non-null     object
dtypes: object(11)
memory usage: 2.3+ KB

In [59]:
df["DT"] = pd.to_datetime(df["DT"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   STK_CD       25 non-null     object
 1   STK_NM       25 non-null     object
 2   SEC_NM       25 non-null     object
 3   EX_CD        25 non-null     object
 4   DT           25 non-null     datetime64[ns]
 5   O_PRC        25 non-null     object
 6   L_PRC        25 non-null     object
 7   H_PRC        25 non-null     object
 8   C_PRC        25 non-null     object
 9   VOL          25 non-null     object
 10  FIN_ITM_VAL  25 non-null     object
dtypes: datetime64[ns](1), object(10)
memory usage: 2.3+ KB

In [80]:
# o_prc 컬럼부터 마지막  컬럼까지 숫자형으로 변환
df.loc[  : , "O_PRC": ] = df.loc[  : , "O_PRC": ].astype("int64")

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   STK_CD       25 non-null     object
 1   STK_NM       25 non-null     object
 2   SEC_NM       25 non-null     object
 3   EX_CD        25 non-null     object
 4   DT           25 non-null     datetime64[ns]
 5   O_PRC        25 non-null     object
 6   L_PRC        25 non-null     object
 7   H_PRC        25 non-null     object
 8   C_PRC        25 non-null     object
 9   VOL          25 non-null     object
 10  FIN_ITM_VAL  25 non-null     object
dtypes: datetime64[ns](1), object(10)
memory usage: 2.3+ KB

In [88]:
df["STK_NM"].head(50)

0        동화약품
1        유유제약
2       일동홀딩스
3        삼일제약
4      종근당홀딩스
5          한독
6        국제약품
7        부광약품
8     에이프로젠제약
9        대원제약
10       보령제약
11      우리들제약
12     녹십자홀딩스
13        녹십자
14       일양약품
15       광동제약
16    한올바이오파마
17       신풍제약
18       셀트리온
19       이연제약
20       한미약품
21      동아에스티
22        종근당
23     JW생명과학
24       일동제약
Name: STK_NM, dtype: object

In [89]:
df.rename(columns={"FIN_ITM_VAL" : "주당순이익"}, inplace=True)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   STK_CD  25 non-null     object
 1   STK_NM  25 non-null     object
 2   SEC_NM  25 non-null     object
 3   EX_CD   25 non-null     object
 4   DT      25 non-null     datetime64[ns]
 5   O_PRC   25 non-null     object
 6   L_PRC   25 non-null     object
 7   H_PRC   25 non-null     object
 8   C_PRC   25 non-null     object
 9   VOL     25 non-null     object
 10  주당순이익   25 non-null     object
dtypes: datetime64[ns](1), object(10)
memory usage: 2.3+ KB

In [92]:
df["PER"] = df["C_PRC"] / df["주당순이익"]
df

,STK_CD,STK_NM,SEC_NM,EX_CD,DT,O_PRC,L_PRC,H_PRC,C_PRC,VOL,주당순이익,PER
0,000020,동화약품,제약바이오,KP,2019-01-04,9100,9100,9700,9530,115336,365,26.109589
1,000220,유유제약,제약바이오,KP,2019-01-04,10050,9970,10300,10200,82844,639,15.962441
2,000230,일동홀딩스,제약바이오,KP,2019-01-04,12116,11830,12259,12211,5895,-363,-33.639118
3,000520,삼일제약,제약바이오,KP,2019-01-04,19900,19650,20550,20550,38394,-1621,-12.67736
4,001630,종근당홀딩스,제약바이오,KP,2019-01-04,58600,57800,59800,58400,3773,5481,10.65499
5,002390,한독,제약바이오,KP,2019-01-04,28150,27400,28950,28000,151657,590,47.457627
6,002720,국제약품,제약바이오,KP,2019-01-04,4070,4070,4395,4275,50009,128,33.398438
7,003000,부광약품,제약바이오,KP,2019-01-04,20670,20583,21588,21413,391200,3019,7.092746
8,003060,에이프로젠제약,제약바이오,KP,2019-01-04,1863,1765,1883,1844,477730,-12,-153.666667
9,003220,대원제약,제약바이오,KP,2019-01-04,13865,13685,14000,13955,29095,1263,11.049089
10,003850,보령제약,제약바이오,KP,2019-01-04,8994,8903,9132,9068,128338,483,18.774327
11,004720,우리들제약,제약바이오,KP,2019-01-04,7750,7650,9320,8770,7419524,390,22.487179
12,005250,녹십자홀딩스,제약바이오,KP,2019-01-04,24000,24000,24750,24600,64634,406,60.591133
13,006280,녹십자,제약바이오,KP,2019-01-04,129500,129000,134500,133000,38323,3017,44.083527
14,007570,일양약품,제약바이오,KP,2019-01-04,26000,25850,27850,27800,70990,-269,-103.345725
15,009290,광동제약,제약바이오,KP,2019-01-04,6610,6400,6690,6690,149423,551,12.141561
16,009420,한올바이오파마,제약바이오,KP,2019-01-04,31900,31700,34550,34200,789924,64,534.375
17,019170,신풍제약,제약바이오,KP,2019-01-04,6110,6110,6850,6840,1526914,56,122.142857
18,068270,셀트리온,제약바이오,KP,2019-01-04,197428,195083,207276,206338,1207224,2100,98.25619
19,102460,이연제약,제약바이오,KP,2019-01-04,13976,13486,14222,14222,20559,81,175.580247
20,128940,한미약품,제약바이오,KP,2019-01-04,422320,417981,436783,435336,38436,2201,197.790095
21,170900,동아에스티,제약바이오,KP,2019-01-04,102000,102000,107500,106000,27461,949,111.696523
22,185750,종근당,제약바이오,KP,2019-01-04,89537,89082,91809,90718,24980,4313,21.033619
23,234080,JW생명과학,제약바이오,KP,2019-01-04,20750,20000,20950,20900,82687,999,20.920921
24,249420,일동제약,제약바이오,KP,2019-01-04,19450,19350,19950,19800,51197,589,33.616299

In [93]:
df[["STK_CD", "STK_NM", "PER"]]

    STK_CD   STK_NM         PER
0   000020     동화약품   26.109589
1   000220     유유제약   15.962441
2   000230    일동홀딩스  -33.639118
3   000520     삼일제약   -12.67736
4   001630   종근당홀딩스    10.65499
5   002390       한독   47.457627
6   002720     국제약품   33.398438
7   003000     부광약품    7.092746
8   003060  에이프로젠제약 -153.666667
9   003220     대원제약   11.049089
10  003850     보령제약   18.774327
11  004720    우리들제약   22.487179
12  005250   녹십자홀딩스   60.591133
13  006280      녹십자   44.083527
14  007570     일양약품 -103.345725
15  009290     광동제약   12.141561
16  009420  한올바이오파마     534.375
17  019170     신풍제약  122.142857
18  068270     셀트리온    98.25619
19  102460     이연제약  175.580247
20  128940     한미약품  197.790095
21  170900    동아에스티  111.696523
22  185750      종근당   21.033619
23  234080   JW생명과학   20.920921
24  249420     일동제약   33.616299